const DEMO_ZONES = [
  {
    id: "owner_cabin",
    name: "Owner Cabin",
    deck: "Main Deck",
    room: "Owner Suite",
    manufacturer: "frigomar",
    protocol: "mock",
    online: true,
    currentTemperature: 22.5,
    targetTemperature: 22,
    humidity: 52,
    mode: "cool",
    fanSpeed: "medium",
    powerState: "on",
    valveStatus: 65,
    compressorStatus: true,
    alarmStatus: false,
    alarmCode: "0",
  },
  {
    id: "vip_cabin",
    name: "VIP Cabin",
    deck: "Main Deck",
    room: "VIP Suite",
    manufacturer: "dometic",
    protocol: "mock",
    online: true,
    currentTemperature: 23.0,
    targetTemperature: 23,
    humidity: 48,
    mode: "auto",
    fanSpeed: "low",
    powerState: "on",
    valveStatus: 45,
    compressorStatus: true,
    alarmStatus: false,
    alarmCode: "0",
  },
  {
    id: "guest_cabin_port",
    name: "Guest Cabin Port",
    deck: "Lower Deck",
    room: "Guest Cabin Port",
    manufacturer: "condaria",
    protocol: "mock",
    online: true,
    currentTemperature: 21.0,
    targetTemperature: 22,
    humidity: 55,
    mode: "heat",
    fanSpeed: "auto",
    powerState: "on",
    valveStatus: 30,
    compressorStatus: false,
    alarmStatus: false,
    alarmCode: "0",
  },
  {
    id: "guest_cabin_stbd",
    name: "Guest Cabin Starboard",
    deck: "Lower Deck",
    room: "Guest Cabin Starboard",
    manufacturer: "frigomar",
    protocol: "mock",
    online: false,
    currentTemperature: 19.5,
    targetTemperature: 22,
    humidity: null,
    mode: "off",
    fanSpeed: "auto",
    powerState: "off",
    valveStatus: 0,
    compressorStatus: false,
    alarmStatus: true,
    alarmCode: "E-02",
  },
  {
    id: "main_saloon",
    name: "Main Saloon",
    deck: "Main Deck",
    room: "Saloon",
    manufacturer: "condaria",
    protocol: "mock",
    online: true,
    currentTemperature: 24.0,
    targetTemperature: 24,
    humidity: 45,
    mode: "cool",
    fanSpeed: "high",
    powerState: "on",
    valveStatus: 80,
    compressorStatus: true,
    alarmStatus: false,
    alarmCode: "0",
  },
  {
    id: "bridge",
    name: "Bridge",
    deck: "Upper Deck",
    room: "Wheelhouse",
    manufacturer: "dometic",
    protocol: "mock",
    online: true,
    currentTemperature: 25.0,
    targetTemperature: 24,
    humidity: 40,
    mode: "cool",
    fanSpeed: "auto",
    powerState: "on",
    valveStatus: 55,
    compressorStatus: true,
    alarmStatus: false,
    alarmCode: "0",
  },
  {
    id: "crew_mess",
    name: "Crew Mess",
    deck: "Lower Deck",
    room: "Crew Mess",
    manufacturer: "frigomar",
    protocol: "mock",
    online: true,
    currentTemperature: 20.0,
    targetTemperature: 21,
    humidity: 58,
    mode: "heat",
    fanSpeed: "low",
    powerState: "on",
    valveStatus: 25,
    compressorStatus: false,
    alarmStatus: false,
    alarmCode: "0",
  },
  {
    id: "galley",
    name: "Galley",
    deck: "Main Deck",
    room: "Galley",
    manufacturer: "generic",
    protocol: "mock",
    online: true,
    currentTemperature: 26.0,
    targetTemperature: 24,
    humidity: 60,
    mode: "cool",
    fanSpeed: "high",
    powerState: "on",
    valveStatus: 90,
    compressorStatus: true,
    alarmStatus: false,
    alarmCode: "0",
  },
];

let demoState = JSON.parse(JSON.stringify(DEMO_ZONES));

export function getDemoHVACZones() {
  for (const zone of demoState) {
    if (zone.online && zone.powerState === "on") {
      const drift = (Math.random() - 0.5) * 0.2;
      if (zone.currentTemperature != null) {
        zone.currentTemperature = Math.round((zone.currentTemperature + drift) * 10) / 10;
      }
      if (zone.humidity != null) {
        zone.humidity = Math.round((zone.humidity + (Math.random() - 0.5) * 1) * 10) / 10;
      }
    }
  }
  return demoState.map((z) => ({ ...z }));
}

export function resetDemoHVAC() {
  demoState = JSON.parse(JSON.stringify(DEMO_ZONES));
}
